# Generated by Django 6.0.2 on 2026-02-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompttemplate',
            name='template_type',
            field=models.CharField(choices=[('generation', 'Generation'), ('edit', 'Edit/Smart Action')], default='generation', max_length=20),
        ),
    ]
